spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://Yassine:yassine@cluster0.6wjuxgy.mongodb.net/your-database-name?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.repositories.type=none
